print()
print("-----------------FORMULAIRE DE RENSEIGNEMENT--------")
print()
nom=input("veuillez saisir votre nom s'il vous plait : ")
prenom=input("veuillez saisir votre prenom s'il vous plait : ")
age=int(input("veuillez saisir votre age s'il vous plait : "))
matricule=int(input("veuillez saisir votre matricule s'il vous plait : "))
date_naissance=int(input("veuillez saisir votre date_naissance s'il vous plait : "))
lieu_naissance =input("veuillez saisir votre lieu_naissance s'il vous plait : ")
nationalite=input("veuillez saisir votre nationalite s'il vous plait : ")
niveau_etude=input("veuillez saisir votre niveau_etude s'il vous plait : ")
etablissement=input("veuillez saisir votre etablissement s'il vous plait : ")
print()
print("           BIENVENUE A L'UNIVERSITE  monsieurs/madames",nom,prenom)
print()
print(" nom               : ",nom)
print(" prenom            : ",prenom)
print(" age               : ",age," ans")
print(" matricule         : ",matricule)
print(" date_naissance    : ",date_naissance)
print(" lieu_naissance    : ",lieu_naissance)
print(" nationalite       : ",nationalite)
print(" niveau_etude      : ",niveau_etude)
print(" etablissement     : ",etablissement)
