import math
terme1=int(input("veuillez saisir le premier terme s'il vous plait : "))
terme2=int(input("veuillez saisir le deuxieme terme s'il vous plait : "))
print()
print("la somme de ",terme1,"et", terme2,"est egale a ", terme1+terme2)
print("la soustrction de ",terme1,"et", terme2,"est egale a ", terme1-terme2)
print("la multiplication de ",terme1,"et", terme2,"est egale a ", terme1*terme2)
print("la la division  de ",terme1,"et", terme2,"est egale a ", terme1/terme2)
print("la puissance  de ",terme1,"et", terme2,"est egale a ", terme1**terme2)
print("le reste la division de ",terme1,"et", terme2,"est egale a ", terme1%terme2)
print("le le quotient de la division  de ",terme1,"et", terme2,"est egale a ", terme1//terme2)
print("la racine carée de ",terme1,"est ",math.sqrt(terme1) ,"et la racine carrée de ",terme2,"est",format(math.sqrt(terme2,".2f") ))
print("la multiplication de ", terme1,"par pi est",terme1*(math.pi))
print("la multiplication de ", terme2,"par pi est",terme2*(math.pi))